{{- $stage := .Values.stage }}
{{- $cluster := .Values.cluster }}
{{- $namespace := .Values.namespace }}
{{- range $app := .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $stage }}-{{ $app.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: registry-1.docker.io/devstackhub
    chart: dox-cli
    targetRevision: 1.0.38-helm
    helm:
      parameters:
        - name: image.repository
          value: devstackhub/{{ $app.name }}
        - name: service.name
          value: {{ $app.name }}
        - name: deployment.stage
          value: {{ $stage }}
      values: |
        {{ $app | toYaml | nindent 8 }}
  destination:
    server: {{ $cluster }}
    namespace: {{ $namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
