stage: dev
namespace: dev
cluster: https://kubernetes.default.svc
applications:
  - name: springboot-hello-world
    image:
      tag: 20250424.193641.0
  - name: dox-demo-maven-springboot
    image:
      tag: 20250731.152503.0
  - name: job-orchestrator
    serviceAccount:
      name: orchestrator-sa
    image:
      tag: 20250819.174734.0
